name: NodeJS with Webpack

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for release-please to access git history

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          npm install -g release-please
          release-please release-pr \
            --token=${{ secrets.GITHUB_TOKEN }} \
            --repo-url=${{ github.repository }} \
            --package-name=${{ github.event.repository.name }} \
            --release-type=simple \
            --versioning-strategy=increment-patch \
            --initial-version=1.0.0

      - name: Publish Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: ${{ github.event.repository.name }}
          versioning-strategy: increment-patch
          initial-version: 1.0.0
